name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: # This lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: JA-IN
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23c2abe4&color_dots=%23161b22,%234b3869,%23664c8f,%238666be,%23c2abe4

      - name: Push to Output Branch
        uses: crazy-max/githubaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
